<a href="https://colab.research.google.com/github/ZonaQuant/Notebooks/blob/main/Te_damos_la_bienvenida_a_Colaboratory_df.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
!pip install p123api
import p123api

!pip install pandas
import pandas as pd

try:
    client = p123api.Client(api_id= '42', api_key='6671de78fbf56abb7a171dbd34e6f499')  #Replace with your API id and key
    
    
    df = client.rank_ranks(
        {
            "rankingSystem": "Core: Value",
            "asOfDt": "2020-11-12",
            # Optional parameters
            "pitMethod": "Prelim",  #Prelim or Complete
            "precision": 2,  # 2,3,4
            "rankingMethod": 2, #2-Percentile NAs Negative, 4-Percentile NAs Neutral
            "universe": "DJIA",
            "tickers": "IBM,MSFT",
            "includeNames": False,
            "includeNaCnt": False,
            "includeFinalStmt": False,
            "nodeDetails": "composite",
            "additionalData": ["Close(0)","mktcap","ZScore(\"Pr2SalesQ\",#All)"]
        }, True)
    print(df)

except p123api.ClientException as e:
    print(e)

Requirement already satisfied: p123api in /usr/local/lib/python3.7/dist-packages (1.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.1.5)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
   p123Uids tickers  ranks  ...  formula1    formula2  formula3
0      4737     IBM  86.67  ...    114.04   101616.16       0.0
1      5881    MSFT  20.00  ...    223.72  1692218.09       0.0

[2 rows x 10 columns]

In [10]:
df

   p123Uids tickers  ranks  ...  formula1    formula2  formula3
0      4737     IBM  86.67  ...    114.04   101616.16       0.0
1      5881    MSFT  20.00  ...    223.72  1692218.09       0.0

[2 rows x 10 columns]